plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lgvr.r100'
    compileSdk 34

    defaultConfig {
        applicationId 'com.lgvr.r100'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '0.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
